Some restyling on AddPost buttons and PetList
00frank/patitapp pull request #10
Opened 2021-11-16 20:57 UTC by jsanchezperuga

2021-11-16 21:22 UTC, 00frank requested changes

2021-11-16 21:22 UTC, 00frank commented on screens/Home.js
> +    <View style={{ flex: 1 ,marginTop:10}}>
con el identado deberia quedar asi
```<View style={{ flex: 1, marginTop: 10 }}>```

o identar todo el archivo

2021-11-17 00:37 UTC, jsanchezperuga commented on screens/Home.js
> +    <View style={{ flex: 1 ,marginTop:10}}>
Siempre me olvido...
Ya lo resuelvo!
Listo! Va el PR.

2021-11-17 00:51 UTC, closed without merging

2021-11-17 00:52 UTC, jsanchezperuga commented
Document formatted